import Foundation

extension CleanTargetRegistry {
    /// Android Studio and the emulator, beyond Gradle caches and AVDs.
    static func androidStudioTargets(home: URL) -> [CleanTarget] {
        var targets: [CleanTarget] = []

        let logDirs = versionedChildren(
            of: home.appendingPathComponent("Library/Logs", isDirectory: true),
            prefix: "AndroidStudio"
        )
        if !logDirs.isEmpty {
            targets.append(CleanTarget(
                id: "android-studio-logs",
                name: "Android Studio Logs",
                subtitle: tildePath(home) + "/Library/Logs/AndroidStudio*",
                safetyNote: "IDE log files only; Android Studio regenerates them on the next launch.",
                strategy: .deletePaths(logDirs),
                requiresStrongConfirm: false,
                isPermanent: false
            ))
        }

        let captureDirs = androidStudioCaptureSubfolders(home: home)
        if !captureDirs.isEmpty {
            targets.append(CleanTarget(
                id: "android-studio-captures",
                name: "Android Studio Captures & Heap Dumps",
                subtitle: tildePath(home) + "/Library/Caches/Google/AndroidStudio*/captures",
                safetyNote: "Profiler captures and .hprof heap dumps saved by Android Studio; "
                    + "safe to remove once you've reviewed them. Only these subfolders are touched — "
                    + "the rest of Android Studio's system directory (indexes, local history) is left alone.",
                strategy: .deletePaths(captureDirs),
                requiresStrongConfirm: false,
                isPermanent: false
            ))
        }

        let heapDump = home.appendingPathComponent("java_error_in_studio.hprof")
        if FileManager.default.fileExists(atPath: heapDump.path) {
            targets.append(CleanTarget(
                id: "android-studio-oom-heap-dump",
                name: "Android Studio Crash Heap Dump",
                subtitle: tildePath(heapDump),
                safetyNote: "Written when Android Studio runs out of memory and crashes; safe to remove once reviewed.",
                strategy: .deletePaths([heapDump]),
                requiresStrongConfirm: false,
                isPermanent: false
            ))
        }

        let emulatorCache = home.appendingPathComponent(".android/cache", isDirectory: true)
        if FileManager.default.fileExists(atPath: emulatorCache.path) {
            targets.append(CleanTarget(
                id: "android-emulator-cache",
                name: "Android Emulator Cache",
                subtitle: tildePath(emulatorCache),
                safetyNote: "Regenerated by the emulator and adb as needed.",
                strategy: .deletePaths([emulatorCache]),
                requiresStrongConfirm: false,
                isPermanent: false
            ))
        }

        return targets
    }

    private static func versionedChildren(of directory: URL, prefix: String) -> [URL] {
        guard let children = try? FileManager.default.contentsOfDirectory(
            at: directory,
            includingPropertiesForKeys: nil,
            options: [.skipsHiddenFiles]
        ) else { return [] }
        return children.filter { $0.lastPathComponent.lowercased().hasPrefix(prefix.lowercased()) }
    }

    /// Only `captures`/`heapdumps` — never the versioned system directory itself, which is live
    /// IDE state while Android Studio is running.
    private static func androidStudioCaptureSubfolders(home: URL) -> [URL] {
        let systemDirs = versionedChildren(
            of: home.appendingPathComponent("Library/Caches/Google", isDirectory: true),
            prefix: "AndroidStudio"
        )
        return systemDirs.flatMap { systemDir in
            ["captures", "heapdumps"]
                .map { systemDir.appendingPathComponent($0, isDirectory: true) }
                .filter { FileManager.default.fileExists(atPath: $0.path) }
        }
    }
}
